<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UsersTableSeeder extends Seeder
{
    /**
     * Seed the application's users from a snapshot of the current database.
     */
    public function run(): void
    {
        $users = [
            0 => [
                'id' => 1,
                'name' => 'Super Admin',
                'email' => 'superadmin@email.com',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/u9vw6dQDxvOnhDEFy36B0yVvRLKTww4jjRtf1aes.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$tOoaTY35U2tneaj4N5ANLOZaQ2hqjcJcZ/dDuUAlDyU09dDu1M3cG',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2023-04-13 19:47:27',
                'updated_at' => '2026-03-05 11:25:27',
                'is_default_password' => 0,
                'manager_id' => null,
            ],
            1 => [
                'id' => 2,
                'name' => 'Sendy Shibambo',
                'email' => 'sendy.shibambo@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/sorW2h8ZgClR3HXUISWWfXpe6zmJkOV0xvNroIUa.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'jbAMuEiJVDtfrgd68FQeRTjdynajnaNpeprcI8Fmd6b9NjyImT8vBRln8wE7',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2024-09-02 15:25:23',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            2 => [
                'id' => 4,
                'name' => 'Kwaku Bonsu',
                'email' => 'kwaku.bonsu@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/DGKjF8j2toEOsdSqMv2X5PIm5G9fQ1jPY3PG5xr1.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$5RXRfQ4qo7BIw1i0C02/COyszsYNTtNnaqWUAg17Wg4p4eb4n4f0e',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => '3K64oqssfuKCWif3B1IsEXldCXf5tWtTXObsMsjFmVqAX0Bc8h3dTKxi8kJY',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2026-03-05 11:50:26',
                'is_default_password' => 0,
                'manager_id' => 8,
            ],
            3 => [
                'id' => 5,
                'name' => 'Jennifer Adjei',
                'email' => 'jennifer.adjei@anagkazofacilities.org',
                'is_active' => 0,
                'profile_photo_path' => 'profile-photos/GxKMHbXRwmDkkHE5qV4eIB5BkgJ41t5D7D57PnR9.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'WwSFxZpKOGzpqBmAuGMOsLwguKf3MEZAj1GrXHAtuDYqAGdW0fvz5tfiHHwE',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2026-03-01 21:54:52',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            4 => [
                'id' => 6,
                'name' => 'Davidson Aflo',
                'email' => 'davidson.aflo@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/AA0aU8E9ZvpLxBx21rz6rOUGwUr37syuqkZKni6R.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'l6hguoQo3ZHMi8uPB7AjgumCRyp5H07BmDRbPWeFeEGlqMMpn6QK4qfMkcpx',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2024-02-12 05:30:58',
                'is_default_password' => 1,
                'manager_id' => 8,
            ],
            5 => [
                'id' => 7,
                'name' => 'Gloria Musa',
                'email' => 'gloria.musa@anagkazofacilities.org',
                'is_active' => 0,
                'profile_photo_path' => 'profile-photos/L2P3IaU4jJu0dopE8rTmvzv1kOuo7uC09n9RbDSn.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'RiPDqFGxJkEgSKM5OIHSoBfO02ZVqLXLyPeStoeuzo7x6tlMEmMmfJOc5LMk',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2026-03-01 21:56:08',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            6 => [
                'id' => 8,
                'name' => 'Kumah Agyeman',
                'email' => 'kumah.agyeman@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/D0sGlHZ3HjY5fA3HAgrQe7gJjG9vziJVTc0dYar7.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$H0.gjpF55GV0pOJcmg4uYuL8QysWNP8fwT4r2NegE2kjaL9YLmv7m',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'uuNispraTOH8NQA3EcYkbW22Q6Gzc6I84SeE29sYBjvMuXnQDVKN5yIX5GXF',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2026-03-06 20:04:24',
                'is_default_password' => 0,
                'manager_id' => null,
            ],
            7 => [
                'id' => 9,
                'name' => 'Nana Penny',
                'email' => 'nana.penny@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/rOlMJ166P3x89RSgsnlLzpubywofMNT75KdiHd93.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'wUPSc4LE7vhvxuryPbB8eiZ545xWo5NRftwZatHu5VQ9qD3LOtC915Ows83u',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2024-09-02 15:27:19',
                'is_default_password' => 1,
                'manager_id' => 10,
            ],
            8 => [
                'id' => 10,
                'name' => 'Michaela Sowah',
                'email' => 'michaella.sowah@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/N3WLVFbdgQjyJTy1KwBrKMT78KoXaD2VmkCSJ2BW.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'LyWC1OBzHrU5Uw7TTVncnY7CUd6K10Jm7Vy5k6eoqgn88dfIuILhbGl6Jlb7',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2024-09-02 15:29:44',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            9 => [
                'id' => 11,
                'name' => 'Clara Aggrey',
                'email' => 'clara.aggrey@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/gR0OcaGcnVP9Al3irQ7OBhSfsJZEg1dJ4PrAfAtB.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$uMTIGpnkrvFIr1lfmych1em4XYVNfHdFvYgRKiUulciMSSCvaogUi',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'WA3EbKcRdWClEXxIBjHpsAmeFu0TQoNijSRkQ7DtrLTbgG7i4CfhQZbc7EmP',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2026-03-05 12:18:20',
                'is_default_password' => 0,
                'manager_id' => 2,
            ],
            10 => [
                'id' => 12,
                'name' => 'David Williams',
                'email' => 'david.Williams@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/HhDENq4CrglMltLOi4LTGgQqGfuEw00p9Tx6hUDq.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'VUJumFxqQ0yu6DaNQGOzM4T3CHXF9eGNPTmcrAE8XwdWhmpaaZxGfqwhmXrP',
                'created_at' => '2023-04-13 19:47:37',
                'updated_at' => '2024-09-02 15:28:49',
                'is_default_password' => 1,
                'manager_id' => 8,
            ],
            11 => [
                'id' => 13,
                'name' => 'Ruth Appiah-Denkyira',
                'email' => 'ruth@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/rHtp1asues8s7cMpGPBlHUbHyOjd4PNWwIJygTGp.jpg',
                'email_verified_at' => '2023-04-13 19:47:37',
                'password' => '$2y$12$xkV0Xft.jHveREZ/EBHGRuzSixmdj2jDX1Jdaa1ADLB3BONW.8vx2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'PCa25brGZgGLx3DhwAjxlnSZ7fwa2z4t9BVJYEZtYE5ODnO76pZoBRppFlse',
                'created_at' => '2023-04-13 19:47:38',
                'updated_at' => '2026-03-05 11:35:04',
                'is_default_password' => 0,
                'manager_id' => null,
            ],
            12 => [
                'id' => 15,
                'name' => 'Mercy Asomani',
                'email' => 'mercy.asomani@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/KQr0liM6gO7PpzgyU8DAi5MvYqywZQHsA7HLb0YY.jpg',
                'email_verified_at' => '2023-04-14 03:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => '1DY5Yu4AfOiEuH9FZBYpEclzYroVCo0DTYA9lLLpDXkpuNvC6aZgUioFW4Vg',
                'created_at' => '2023-04-14 03:47:37',
                'updated_at' => '2026-03-05 09:46:10',
                'is_default_password' => 1,
                'manager_id' => 2,
            ],
            13 => [
                'id' => 16,
                'name' => 'Solange Dondi',
                'email' => 'solange.dondi@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/v6XaL628Ur8cbaynUJRdYcMkrzIcKLJ0VYA03r5y.jpg',
                'email_verified_at' => '2023-04-14 03:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => 'NIbG3TC4TrBOvqln3MRuELfDGAZCHhVIRYLvo2SmSLJ8LMTkFaaMmYNleD4B',
                'created_at' => '2023-04-14 03:47:37',
                'updated_at' => '2026-03-05 02:54:39',
                'is_default_password' => 1,
                'manager_id' => 10,
            ],
            14 => [
                'id' => 17,
                'name' => 'Shakiel Griffith',
                'email' => 'shakiel.griffith@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/aDJBsIgM24Tjy6g8iiLvyxMF67DusYbtro2tBB3f.jpg',
                'email_verified_at' => '2023-04-14 03:47:37',
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => '0uxlkoANnccCo4F6ll0YulVTRR8rpdRRHyc3rClQuHrXVQSEdqkqG4tENawh',
                'created_at' => '2025-02-24 03:47:37',
                'updated_at' => '2025-04-21 00:11:50',
                'is_default_password' => 1,
                'manager_id' => 10,
            ],
            15 => [
                'id' => 18,
                'name' => 'Kwadwo Bonsu',
                'email' => 'kwadwo.bonsu@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/R4i5FHqikdwWTi3RH8xy11Do3y8LHFp5KTG7wtGF.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$lk5aRui/mKPWXt5MAdXPP.ior/431tctaSc04BQ32le9mKDLieG2W',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => '2026-03-06 19:49:53',
                'is_default_password' => 0,
                'manager_id' => 8,
            ],
            16 => [
                'id' => 21,
                'name' => 'Maintenance Manager',
                'email' => 'mm@anagkazofacilities.org',
                'is_active' => 0,
                'profile_photo_path' => 'profile-photos/R4i5FHqikdwWTi3RH8xy11Do3y8LHFp5KTG7wtGF.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => '2026-03-01 21:56:29',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            17 => [
                'id' => 22,
                'name' => 'Manager',
                'email' => 'manager@email.com',
                'is_active' => 0,
                'profile_photo_path' => 'profile-photos/R4i5FHqikdwWTi3RH8xy11Do3y8LHFp5KTG7wtGF.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => null,
                'updated_at' => '2026-03-01 21:56:35',
                'is_default_password' => 1,
                'manager_id' => null,
            ],
            18 => [
                'id' => 23,
                'name' => 'Whitney Ballestero-Lepiz',
                'email' => 'whitney.ballestero@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/JcJ9s7PyU9sqmb6i12UcViMRPRHtFMVdDwZvO9Ot.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-03-01 20:17:24',
                'updated_at' => '2026-03-05 09:42:03',
                'is_default_password' => 1,
                'manager_id' => 2,
            ],
            19 => [
                'id' => 24,
                'name' => 'Ashlee Williams',
                'email' => 'ashlee.williams@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/mqwUiAWFyxlwiKGXXB9YECQ6IbezAZwfnPAK2Nww.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-03-01 20:36:49',
                'updated_at' => '2026-03-05 09:52:06',
                'is_default_password' => 1,
                'manager_id' => 10,
            ],
            20 => [
                'id' => 25,
                'name' => 'Rejoice Amartey',
                'email' => 'rejoice.amartey@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/JjiMfkE43eg0SR75NpkKualxiWRAVxbVu3UuQUKA.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-03-01 20:37:16',
                'updated_at' => '2026-03-05 09:43:04',
                'is_default_password' => 1,
                'manager_id' => 2,
            ],
            21 => [
                'id' => 26,
                'name' => 'Linda Sakyi',
                'email' => 'linda.sakyi@anagkazofacilities.org',
                'is_active' => 1,
                'profile_photo_path' => 'profile-photos/rV2FkwlOYsiuIbBnlKEOFqIUantrfPNPfzWdXUmt.jpg',
                'email_verified_at' => null,
                'password' => '$2y$12$UFvv.pLorgYVi6I5OlEELOgxRu9XIxpfZhqF9pm6JHhk.1GOVV3J2',
                'two_factor_secret' => null,
                'two_factor_recovery_codes' => null,
                'two_factor_confirmed_at' => null,
                'remember_token' => null,
                'created_at' => '2026-03-05 08:20:47',
                'updated_at' => '2026-03-05 09:51:02',
                'is_default_password' => 1,
                'manager_id' => 8,
            ],
        ];

        if ($users === []) {
            return;
        }

        Schema::disableForeignKeyConstraints();

        DB::table('users')->upsert(
            $users,
            ['id'],
            [
                'name',
                'email',
                'is_active',
                'profile_photo_path',
                'email_verified_at',
                'password',
                'two_factor_secret',
                'two_factor_recovery_codes',
                'two_factor_confirmed_at',
                'remember_token',
                'created_at',
                'updated_at',
                'is_default_password',
                'manager_id',
            ]
        );

        Schema::enableForeignKeyConstraints();
    }
}
